### ISSUE TITLE
ValueError: GRU(reset_after=False) is not compatible with GRU(reset_after=True)

### ISSUE THREAD

**Issue by Muhammad-Zubair** [ashnkumar/sketch-code#34]
**This Error occurred when try to execute even on example png file included in examples folder:-**

2020-12-20 13:24:45.775351: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.1
2020-12-20 13:24:48.621379: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2020-12-20 13:24:48.623512: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcuda.so.1
2020-12-20 13:24:48.634334: E tensorflow/stream_executor/cuda/cuda_driver.cc:328] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2020-12-20 13:24:48.634394: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (499992af94a2): /proc/driver/nvidia/version does not exist
2020-12-20 13:24:48.634936: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
Traceback (most recent call last):
  File "convert_single_image.py", line 53, in <module>
    main()
  File "convert_single_image.py", line 49, in main
    model_weights_path = model_weights_file)
  File "/content/drive/My Drive/testp2c/sketch-code/src/classes/inference/Sampler.py", line 23, in __init__
    self.model = self.load_model(model_json_path, model_weights_path)
  File "/content/drive/My Drive/testp2c/sketch-code/src/classes/inference/Sampler.py", line 74, in load_model
    loaded_model.load_weights(model_weights_path)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py", line 2234, in load_weights
    hdf5_format.load_weights_from_hdf5_group(f, self.layers)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/saving/hdf5_format.py", line 700, in load_weights_from_hdf5_group
    layer, weight_values, original_keras_version, original_backend)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/saving/hdf5_format.py", line 410, in preprocess_weights_for_loading
    return _convert_rnn_weights(layer, weights)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/saving/hdf5_format.py", line 571, in _convert_rnn_weights
    raise ValueError('%s is not compatible with %s' % types)
**ValueError: GRU(reset_after=False) is not compatible with GRU(reset_after=True)**

**Comment by karynaur** [comment]
`pip install -r requirements.txt` should remove the error.
The code is written in tensorflow 1.x while you are trying to run it on tensorflow 2.x
