### ISSUE TITLE
The training data is not available!

### ISSUE THREAD

**Issue by ace-wangyuzhen** [ashnkumar/sketch-code#60]
![image](https://github.com/ashnkumar/sketch-code/assets/39297643/f93bc46d-6e0d-4042-b2e4-28a911988c26)

**Comment by xiahao-china** [comment]
I had the same problem

**Comment by josue2609** [comment]
I have the same issue.

**Comment by yhhPP** [comment]
same issue. so ...then...?

**Comment by jtshushu** [comment]
(py36) E:\koutu\on_web\sketch-code\src>python convert_single_image.py --png_path ../examples/drawn_example1.png  --output_folder ./generated_html  --model_json_file ../bin/model_json.json  --model_weights_file ../bin/weights.h5
Using TensorFlow backend.
Traceback (most recent call last):
  File "convert_single_image.py", line 53, in <module>
    main()
  File "convert_single_image.py", line 49, in main
    model_weights_path = model_weights_file)
  File "E:\koutu\on_web\sketch-code\src\classes\inference\Sampler.py", line 23, in __init__
    self.model = self.load_model(model_json_path, model_weights_path)
  File "E:\koutu\on_web\sketch-code\src\classes\inference\Sampler.py", line 70, in load_model
    json_file = open(model_json_path, 'r')
FileNotFoundError: [Errno 2] No such file or directory: '../bin/model_json.json'

Hello, how can I solve the problem?

**Comment by DhruvGarg111** [comment]
the data is available on kaggle , use this.

import kagglehub

# Download latest version
path = kagglehub.dataset_download("vshantam/sketch2code")

print("Path to dataset files:", path)
